name: dotnet-sdk
version: 2.0.0
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core 2.0.0 SDK. https://dot.net/core.

grade: devel
confinement: devmode

apps:
  dotnet-sdk:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home
parts:
  dotnet-sdk:
      plugin: dump
      source: http://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-linux-x64.tar.gz
      source-checksum: sha256/6059a6f72fb7aa6205ef4b52583e9c041fd128e768870a0fc4a33ed84c98ca6b
      stage-packages:
        - libicu55
        - libssl1.0.0
        - libc6
        - libcurl3
        - libgssapi-krb5-2
        - liblttng-ust0
        - libstdc++6
        - zlib1g
        - libgcc1
        - lldb
        - libunwind8



