name: dotnet-runtime
version: 2.0.0
summary: Cross-Platform .NET Core Runtime. 
description: |
  .NET Core 2.0.0 Runtime. https://dot.net/core.

grade: devel
confinement: devmode

apps:
  dotnet:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home

slots:
  # This is how we make a part of this snap readable by other
  # snaps. Consumers will need to access the runtime as well
  # as various libs contained in this snap, so share the entire
  # $SNAP
  dotnet-runtime:
    content: dotnet-runtime
    interface: content
    read: [/]

parts:
  dotnet-runtime:
      plugin: dump
      source: http://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-runtime-2.0.0-linux-x64.tar.gz
      source-checksum: sha256/69ecad24bce4f2132e0db616b49e2c35487d13e3c379dabc3ec860662467b714
      stage-packages:
        - libicu55
        - libssl1.0.0
        - libc6
        - libcurl3
        - libgssapi-krb5-2
        - liblttng-ust0
        - libstdc++6
        - zlib1g
        - libgcc1
        - lldb
        - libunwind8
